default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetin_development
  username: postgres
  password: Partners1
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default
  database: budgetin_test

production:
  <<: *default
  database: budgetin_production
  username: postgres
  password: Partners1
